JMK_RAMDISK_FIRST_TASKS=create_ramdisk_dirs

create_ramdisk_dirs:
	@rm -rf $(DISK_IMAGE_DIR)
	@$(MKDIR) $(DISK_IMAGE_DIR)
	@$(MKDIR) $(RAMDISK_MOUNT_POINT)
	@$(MKDIR) $(JMKE_RAMDISK_DEV_DIR)
	@rm -rf $(BOOTLDR_DISK_IMAGE_DIR)
	@$(MKDIR) $(BOOTLDR_DISK_IMAGE_DIR)
	@$(MKDIR) $(BOOTLDR_RAMDISK_MOUNT_POINT)
	@$(MKDIR) $(BOOTLDR_RAMDISK_DEV_DIR)
