# Autogenerated sources and links should not be exported
# read JMK_AUTOGEN_SRC before it is changed by lang_subdir.mak
JMK_DONT_EXPORT+= $(call Rel_Path_To_Abs,$(JMK_LINKS) $(JMK_AUTOGEN_SRC), \
  $(JMKE_PWD_BUILD)/)

# create a copy of JMK_EXPORT_HEADERS in order to save the list in two separate
# ways
cp_JMK_EXPORT_HEADERS:=$(filter-out $(JMK_AUTOGEN_SRC), $(JMK_EXPORT_HEADERS))
