ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=md4.h
JMK_INTERNAL_HEADERS=md4_locl.h

JMK_O_OBJS=md4_dgst.o md4_one.o

$(call JMKE_INCLUDE_RULES)
