ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS_DIR=libnl/netlink/route/link
JMK_EXPORT_HEADERS=info-api.h vlan.h

$(call JMKE_INCLUDE_RULES)
