JMK_ROOT=../../../../
include $(JMK_ROOT)/envir.mak

JMK_EXPORT_HEADERS_DIR=fuse-lite
JMK_EXPORT_HEADERS+=fuse.h fuse_common.h fuse_lowlevel.h fuse_lowlevel_compat.h \
		fuse_opt.h fuse_kernel.h

include $(JMKE_MK)
