E2FSSRC=../..
include $(E2FSSRC)/envir.mak

JMK_A_TARGET=libuuid.a

JMK_O_OBJS_libuuid.a=clear.o compare.o copy.o gen_uuid.o isnull.o pack.o parse.o \
  unpack.o unparse.o uuid_time.o 

include $(E2FSMK)
