ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=ripemd.h
JMK_INTERNAL_HEADERS=rmd_locl.h rmdconst.h

JMK_O_OBJS=rmd_dgst.o rmd_one.o

$(call JMKE_INCLUDE_RULES)
