ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_SUBDIRS=linux netlink

JMK_EXPORT_HEADERS_DIR=libnl
JMK_EXPORT_HEADERS=netlink-generic.h netlink-local.h netlink-tc.h \
  netlink-types.h

$(call JMKE_INCLUDE_RULES)
