JMK_ROOT=../../../
include $(JMK_ROOT)/envir.mak

JMK_A_TARGET=libevent.a

JMK_O_OBJS=event.o event_tcp.o hash.o event_sig.o
JMK_INTERNAL_HEADERS+=event.h eventpriv.h event_tcp.h hash.h

include $(JMKE_MK)

