ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=whrlpool.h
JMK_INTERNAL_HEADERS=wp_locl.h

WP_ASM_OBJ=wp_block.o
JMK_O_OBJS=wp_dgst.o $(WP_ASM_OBJ)

$(call JMKE_INCLUDE_RULES)
