ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS_DIR=libnl/netlink/cli
JMK_EXPORT_HEADERS=addr.h ct.h link.h Makefile neigh.h qdisc.h route.h \
  rule.h utils.h

$(call JMKE_INCLUDE_RULES)
