ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=dh.h

JMK_O_OBJS=dh_asn1.o dh_gen.o dh_key.o dh_lib.o dh_check.o dh_err.o dh_depr.o \
	   dh_ameth.o dh_pmeth.o dh_prn.o

$(call JMKE_INCLUDE_RULES)

