ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS_DIR=libnl/netlink/fib_lookup
JMK_EXPORT_HEADERS=lookup.h request.h

$(call JMKE_INCLUDE_RULES)
