ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=ecdh.h
JMK_INTERNAL_HEADERS=ech_locl.h

JMK_O_OBJS=ech_lib.o ech_ossl.o ech_key.o ech_err.o

$(call JMKE_INCLUDE_RULES)

