ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=rc2.h
JMK_INTERNAL_HEADERS=rc2_locl.h

JMK_O_OBJS=rc2_ecb.o rc2_skey.o rc2_cbc.o rc2cfb64.o rc2ofb64.o

$(call JMKE_INCLUDE_RULES)
