ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_SUBDIRS=ematch

JMK_EXPORT_HEADERS_DIR=libnl/netlink/route/cls
JMK_EXPORT_HEADERS=basic.h cgroup.h ematch.h fw.h police.h u32.h

$(call JMKE_INCLUDE_RULES)
