ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=rand.h
JMK_INTERNAL_HEADERS=rand_lcl.h

JMK_O_OBJS=md_rand.o randfile.o rand_lib.o rand_err.o rand_egd.o rand_unix.o

$(call JMKE_INCLUDE_RULES)
