ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=conf.h conf_api.h
JMK_INTERNAL_HEADERS=conf_def.h

JMK_O_OBJS=	conf_err.o conf_lib.o conf_api.o conf_def.o conf_mod.o \
	conf_mall.o conf_sap.o

$(call JMKE_INCLUDE_RULES)

