ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_O_TARGET=route-sch.o

JMK_O_OBJS_route-sch.o=blackhole.o cbq.o dsmark.o fifo.o htb.o netem.o \
  prio.o red.o sfq.o tbf.o 

$(call JMKE_INCLUDE_RULES)
