ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_RAMDISK_ETC_FILES+=$(JMKE_PWD_SRC)/pktloc
JMK_JPKG_EXPORTED_FILES+=$(JMKE_PWD_SRC)/pktloc

$(call JMKE_INCLUDE_RULES)
