E2FSSRC=../..
include $(E2FSSRC)/envir.mak

JMK_A_TARGET=libe2p.a

JMK_O_OBJS_libe2p.a=feature.o fgetflags.o fsetflags.o fgetversion.o fsetversion.o \
  getflags.o getversion.o hashstr.o iod.o ls.o mntopts.o \
  pe.o pf.o ps.o setflags.o setversion.o uuid.o

include $(E2FSMK)
