ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS_DIR=libnl/linux
JMK_EXPORT_HEADERS=genetlink.h gen_stats.h if_addr.h if_arp.h if_ether.h \
  if.h if_link.h if_vlan.h ip_mp_alg.h neighbour.h netfilter.h netlink.h \
  pkt_cls.h pkt_sched.h rtnetlink.h

$(call JMKE_INCLUDE_RULES)
