ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=comp.h

JMK_O_OBJS=comp_lib.o comp_err.o c_rle.o c_zlib.o

$(call JMKE_INCLUDE_RULES)

