ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=ecdsa.h
JMK_INTERNAL_HEADERS=ecs_locl.h

JMK_O_OBJS=ecs_lib.o ecs_asn1.o ecs_ossl.o ecs_sign.o ecs_vrf.o ecs_err.o

$(call JMKE_INCLUDE_RULES)

