JMK_ROOT=../../../../
include $(JMK_ROOT)/envir.mak

JMK_EXPORT_HEADERS_DIR=ntfs-3g
JMK_EXPORT_HEADERS+=security.h types.h attrib.h bitmap.h bootsect.h device.h dir.h \
  mft.h mst.h runlist.h layout.h volume.h logging.h device_io.h \
  endians.h support.h inode.h unistr.h debug.h

include $(JMKE_MK)
