ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS_DIR=libnl/netlink/route/sch
JMK_EXPORT_HEADERS=cbq.h dsmark.h fifo.h htb.h netem.h prio.h red.h sfq.h \
  tbf.h

$(call JMKE_INCLUDE_RULES)
