ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=md5.h
JMK_INTERNAL_HEADERS=md5_locl.h

JMK_O_OBJS=md5_dgst.o md5_one.o

$(call JMKE_INCLUDE_RULES)
