ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_SUBDIRS=cls link sch

JMK_EXPORT_HEADERS_DIR=libnl/netlink/route
JMK_EXPORT_HEADERS=addr.h class.h classifier.h classifier-modules.h \
  class-modules.h link.h neighbour.h neightbl.h nexthop.h pktloc.h \
  qdisc.h qdisc-modules.h route.h rtnl.h rule.h tc.h

$(call JMKE_INCLUDE_RULES)
