ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=sha.h sha1dgst.c__c/sha1dgst.c
JMK_INTERNAL_HEADERS=sha_locl.h

JMK_O_OBJS=sha_dgst.o sha1dgst.o sha_one.o sha1_one.o sha256.o sha512.o

$(call JMKE_INCLUDE_RULES)
